# Generated by Django 2.1.5 on 2021-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Best_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='review',
            name='user_list',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
